### ISSUE TITLE
[Info/Request]

### ISSUE THREAD

**Issue by Cookiezzz** [DonElSarjo/elevator#1]
Awesome mod, do you know if it's possible to mod this into the missionfile so no additional Mod would need to be loaded?

If so, am I allowed to try?

**Comment by DonElSarjo** [comment]
for: "Land_Dum_istan2_04a" class DES_GetUpRoof1
private ["_nObject"];
_nObject = [0,0,0] nearestObject 123456; // or find all the "Land_Dum_istan2_04a"
_nObject addaction ["Go to roof", {[player, _nObjectmodelToWorld [2.5227,-4.17255,2.65847], _nObject, (getDir _nObject), 1] spawn des_fnc_teleport}, bka blba lba, {vehicle player == player && {_nObject modelToWorld [-1.19003,-7.04561,-3.96176] distance getPosATL player <= 2} ]; and this for every action. there is a reason i made this via config

**Comment by DonElSarjo** [comment]
try  Zooloo75's Access Points script
